# Generated by Django 3.0.5 on 2020-04-23 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommended', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_image', models.ImageField(upload_to='')),
                ('company_name', models.CharField(max_length=10)),
                ('company_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewLaptopReleases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_name', models.CharField(max_length=50)),
                ('laptop_desc', models.CharField(max_length=200)),
                ('laptop_img', models.ImageField(upload_to='')),
                ('laptop_default_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=10)),
                ('laptop_serial', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('laptop_image', models.ImageField(upload_to='')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommended.Category')),
            ],
        ),
    ]
