# Generated by Django 3.0.5 on 2020-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommended', '0001_initial'),
        ('best_laptops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='category',
        ),
        migrations.AddField(
            model_name='laptop',
            name='category',
            field=models.ManyToManyField(to='recommended.Category'),
        ),
    ]
