# Generated by Django 3.0.5 on 2020-04-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_laptops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
