# Generated by Django 3.0.5 on 2020-04-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_laptops', '0002_auto_20200424_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='laptop_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
