# Generated by Django 3.0.5 on 2020-04-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_laptops', '0002_auto_20200424_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company_desc',
            field=models.CharField(max_length=2000),
        ),
    ]
