# Generated by Django 3.0.3 on 2020-04-26 06:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Msg_from_user',
            new_name='Msgfromuser',
        ),
    ]
